version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  akhq:
    image: tchiotludo/akhq:0.21.0
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8081"
    ports:
      - 8085:8080

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0-1-ubi8
    restart: always
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.0-1-ubi8
    restart: always
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_RETENTION_HOURS: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.0-1-ubi8
    restart: always
    ports:
      - 8081:8081
    container_name: schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: 'forward_transitive'
      KAFKA_REST_CUB_KAFKA_TIMEOUT: 180 # https://github.com/confluentinc/cp-docker-images/issues/807

  create-topics:
    image: confluentinc/cp-kafka:7.0.0-1-ubi8
    container_name: create-topics
    command: >
      bash -c 'echo Waiting for Kafka to be ready... ;
      cub kafka-ready -b kafka:9092 1 300 ;
      echo Creating topics... ;
      kafka-topics --bootstrap-server kafka:9092 \
        --create \
        --topic "hello-world" \
        --partitions 3 \
        --replication-factor 1 ;
      kafka-topics --bootstrap-server kafka:9092 \
        --create \
        --topic "screening" \
        --partitions 3 \
        --replication-factor 1 ;
      true'